id: P006724
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20314
  title: སྤྱི་དམངས་ཀུན་སྤྱོད་ཀྱི་རྒྱུན་ཤེས་ཀློག་དེབ།
  author: ''
  volumes:
    17690063956747e48f8eacc382a60396:
      image_group_id: I8LS20316
      title: ''
      volume_number: 1
      total_pages: 79
